name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_debug_utf8:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Check directories
        run: ls -R

      - name: Configure CMake
        run: cmake -S ./tests/all_tests -B ./tests/all_tests/build -DCMAKE_BUILD_TYPE=Debug -DUSE_UNICODE=OFF

      - name: Build project
        run: cmake --build ./tests/all_tests/build

      - name: Run tests
        run: ./tests/all_tests/build/Varjus
