name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_debug_utf8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      
      - name: Configure CMake
        run: cmake -S . -B tests/all_tests/build -DCMAKE_BUILD_TYPE=Debug -DUSE_UNICODE=OFF 

      - name: Build project
        run: cmake --build tests/all_tests/build

      - name: Check directory 1
        run: ls .
      
      - name: Check directory 2
        run: ls tests/

      - name: Check directory 3
        run: ls tests/all_tests

      - name: Check directory 4
        run: ls tests/all_tests/build

      - name: Run tests
        run: ./Varjus
