name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        unicode: [ON, OFF]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Configure CMake
        run: cmake -S tests/all_tests -B tests/all_tests/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_UNICODE=${{ matrix.unicode }}

      - name: Build project
        run: cmake --build tests/all_tests/build

      - name: Run tests
        run: cd tests/all_tests && ./Varjus

