name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Configure CMake
        run: cmake -S tests/all_tests -B tests/all_tests/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build project
        run: cmake --build tests/all_tests/build

      - name: Run tests
        run: cd tests/all_tests && ./Varjus

  windows_tests:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        unicode: [ON, OFF]
        architecture: [Win32, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -S tests/all_tests -B tests/all_tests/build -A ${{ matrix.architecture }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_UNICODE=${{ matrix.unicode }} -G "Visual Studio 17 2022"

      - name: Build project
        run: cmake --build tests/all_tests/build --config ${{ matrix.build_type }}
          
      - name: Run tests
        run: |
          cd tests/all_tests
          .\Varjus.exe